Work around issue with stale package.json
Commit e8a8d0a introduced several Yarn script, one of which was named
`upgrade-yarn-itself`. That script would call `yarn set version latest`,
followed by an attempt to clean up overzealous changes. I call those
changes `fallout` of the self-upgrade.

However, the fallout would sometimes only occur after the next
invocation of `yarn install`. I tried to incorporate `yarn install`
into the `upgrade-yarn-itself` script, a change that would in turn
introduce the following error message:

> Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.
>
> Source path: /home/claudia/Documents/dev/vscode-taskwarrior/.yarn/releases/yarn-3.2.0.cjs
> Not found: /home/claudia/Documents/dev/vscode-taskwarrior/.yarn/releases/yarn-3.2.0.cjs
>
>     at makeError (/home/claudia/Documents/dev/vscode-taskwarrior/.pnp.cjs:11714:34)
>     at resolveUnqualified (/home/claudia/Documents/dev/vscode-taskwarrior/.pnp.cjs:12710:13)
>     […]

Poking around the PnP scripts leads me to a specific suspicion.
Anytime a Yarn script contains a command that ends up changing the value
of the `packageManager` property in `package.json` (for example,
`yarn set version`), followed by an invocation of `yarn install` while
the same Yarn script is still running, Yarn would – I suspect – continue
using the old `packageManager` value.

However, the cjs file inside .yarn/releases that matches the property
value is no longer there.

As a result, I have no idea how to get Yarn to execute such a script
reliably so I’m replacing the scripts with error messages for now.

A later commit might revisit this issue and, for example, try wrapping
those Yarn invocations inside additional layers of shell processes.